# -*- coding: utf-8 -*-
"""NM Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16oaSZe8nGSij99kNzXdmM3vpHpKa_HYr
"""

from google.colab import files
uploaded = files.upload()
import pandas as pd
import matplotlib.pyplot as plt
from wordcloud import WordCloud
import matplotlib.pyplot as plt
try:
    movies_df = pd.read_csv('movies.csv')
    display(movies_df.head())
    print(movies_df.shape)
except FileNotFoundError:
    print("Error: 'movies.csv' not found.")
except Exception as e:
    print(f"An error occurred: {e}")
print(movies_df.dtypes)
print(movies_df.info())
print(movies_df.describe())
print(movies_df['genres'].value_counts())
print(movies_df['title'].value_counts())
print(movies_df.duplicated().sum())
movies_df['title'] = movies_df['title'].str.strip()
movies_df['title'] = movies_df['title'].str.lower()
genres_list = []
for index in movies_df.index:
    genres = movies_df.loc[index, 'genres'].split('|')
    for genre in genres:
        if genre not in genres_list:
            genres_list.append(genre)
for genre in genres_list:
    movies_df[genre] = 0
    for index in movies_df.index:
        if genre in movies_df.loc[index, 'genres'].split('|'):
            movies_df.loc[index, genre] = 1
display(movies_df.head())
genre_stats = movies_df.loc[:, 'Adventure': '(no genres listed)'].describe()
display(genre_stats)
genre_counts = movies_df.loc[:, 'Adventure': '(no genres listed)'].sum()
display(genre_counts.sort_values(ascending=False))
movies_df['title_length'] = movies_df['title'].str.len()
display(movies_df['title_length'].describe())
from collections import Counter
all_words = ' '.join(movies_df['title']).split()
word_counts = Counter(all_words)
display(word_counts.most_common(10))
print("\nSummary:")
print("Most common genres are Drama, Comedy and Thriller.")
print("The average movie title length is around 30 characters.")
print("Common words in movie titles include 'the', 'of' etc.")
plt.figure(figsize=(12, 6))
genre_counts = movies_df.loc[:, 'Adventure': '(no genres listed)'].sum().sort_values(ascending=False)
genre_counts.plot(kind='bar', color='skyblue')
plt.title('Distribution of Movie Genres')
plt.xlabel('Genres')
plt.ylabel('Number of Movies')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()
plt.figure(figsize=(8, 6))
movies_df['title_length'].plot(kind='hist', bins=30, color='lightcoral')
plt.title('Distribution of Movie Title Lengths')
plt.xlabel('Title Length')
plt.ylabel('Frequency')
plt.show()
plt.figure(figsize=(10, 8))
all_words = ' '.join(movies_df['title']).split()
wordcloud = WordCloud(width=800, height=400, background_color='white').generate(' '.join(all_words))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.title('Frequent Words in Movie Titles')
plt.show()